### ISSUE TITLE
Error of CIELabGamut.m with 'filter' parameter

### ISSUE THREAD

**Issue by kenichiro-masaoka** [CIELab-gamut-tools/gamut-volume-m#17] opened 2024-02-18 06:01 UTC
The following code example (Line 37 in _CIELabGamut.m_) will result in an error although it fits the 4th Syntax (_gamut = CIELabGamut(filepath,filter)_):

```
>> gamut = CIELabGamut('/path/to/folder','*.cgats');
Error using CIELabGamut (line 76)
Unmatched parameter name '/path/to/folder' must be a string scalar or character vector that can
represent a field name. 
```

**Comment by euan-smith** [comment] 2024-02-19 11:30
@kenichiro-masaoka
This seems to be a regression.  This previously worked fine.  Resolving issue 12 or 14 caused this.

**Closed as completed** 2024-02-19 12:08 UTC
Labels: bug
